### ISSUE TITLE
Does this support LTI 1.1 ?

### ISSUE THREAD

**Issue by banister** [instructure/ims-lti#104] opened 2017-03-14 19:10 UTC
If not, do you know of another Ruby gem that supports LTI 1.1 ?

thanks in advance,this looks like a great project

**Comment by bracken** [comment] 2017-03-15 06:09
Yes, it supports LTI 1.1, that is, the ability to send an outcome result

**Comment by rivernate** [comment] 2017-03-15 13:27
The 1.x branch has support for outcome results, the 2.x.* branches don't currently have support.

**Comment by banister** [comment] 2017-03-15 15:57
Thanks. Do you also have support for sending the basic launch and OAuth signing of the payload (for 1.1 basic launch) ?

**Comment by rivernate** [comment] 2017-04-06 21:26
Yes, it does have helper methods for creating a signed lti message

**Comment by banister** [comment] 2017-04-24 14:44
@rivernate thanks, however i can't seem to find the relevant methods in the library. I am trying to generate an http POST payload for the lti launch link, would you be able to point to the relevant methods i use to manage the oauth side of things? thanks!

**Comment by bgibso4** [comment] 2017-06-01 19:04
^I also have this question

**Comment by gordonbisnor** [comment] 2017-09-13 15:39
Would be nice to get some documentation for this library –– I would be happy to fill in some details if I can figure it out. Currently trying to build an LTI product using content-item message and not sure how to do the Content Item Selection POST back to the tool consumer.

**Comment by rivernate** [comment] 2017-11-13 20:42
Duplicate of #141

**Closed by rivernate** 2017-11-13 20:42 UTC
