### ISSUE TITLE
How to use this gem?

### ISSUE THREAD

**Issue by joshfester** [instructure/ims-lti#121] opened 2017-06-07 01:14 UTC
Are there any examples of how to handle the registration process and how to pass data back to the consumer after launch?

**Comment by abutterf** [comment] 2017-06-07 14:05
If you are talking about LTI 2 then you can look at https://github.com/instructure/lti2_reference_tool_provider for an example of the registration process. As far as passing data back to the consumer after launch it depends on what you want to do. If you take users through the oauth process you can use their access token to make api calls to canvas.

**Comment by joshfester** [comment] 2017-06-12 19:27
Thank you. That example app was enough to get me off the ground! However, it does not use this LTI gem. I see no reference anywhere to this gem or it's functions

**Comment by abutterf** [comment] 2017-06-12 20:15
There is another tool https://github.com/instructure/lti_originality_report_example that does use the gem however it doesn't follow the normal registration process because it needs access to a custom tool consumer profile so you won't want to follow that bit of it. But hopefully that will show you how an LTI 2 tool leverages the gem at least for tool registration with Canvas.

**Comment by joshfester** [comment] 2017-06-22 05:03
Thank you @abutterf !

**Comment by rivernate** [comment] 2017-11-13 20:45
Duplicate of #141

**Closed by rivernate** 2017-11-13 20:45 UTC
